title: Blog
tagline: A blog using Chirpy on Netlify
description: >-
  Powered by Jekyll and the Chirpy theme
url: "https://blog.ritwiksaraf.com"
baseurl: ""
lang: en
theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
  collection: posts
